### ISSUE TITLE
missing: PA,P,WS,RH

### ISSUE THREAD

**Issue by Mbnl1197** [aukkola/FLUXNET2015_processing#66]
In the run of **Fluxnet2015/example_conversion_single_site.R**，There was a error:
`Error: Cannot find all essential variables in input file (missing: PA,P,WS,RH), aborting`.

**Comment by JiangJinghong** [comment]
I failed to install the package on Windows11, and I source all the .R file in FluxnetLSM/R. When I try to run the example_conversion_single_site.R, I have the same Error. It seems like resave Site_metadata.csv in FluxnetLSM\data can help. But still have another Error.

**Comment by Mbnl1197** [comment]
Right. This seems to be described in 2.4.1, but it is not clear. 
And it seems that we don't need to enter Site_metadata.csv  to run the program.

**Comment by aukkola** [comment]
The code will only process a site if **all** the essential variables are present in the input file. Otherwise the above error will be returned. These are mainly the meteorological variables needed to drive ecosystem models (since the package was designed for modelling purposes).  You can check which variables are considered "essential" in the Output_variables*.csv files [here](https://github.com/aukkola/FluxnetLSM/tree/master/data) (column _Essential_met_).

If you are processing multiple sites and don't want the code to stop because of an error, you can use "tryCatch" as per [this example](https://github.com/aukkola/FluxnetLSM/blob/master/examples/FLUXNET2015/example_conversion_multiple_sites_parallel.R). Or if you don't want any variables to be considered essential, you can modify the Output_variables*.csv files

**Comment by Mbnl1197** [comment]
Thank you for your reply. I just noticed that the error seems to be a result of multiple time-resolved FLUXNET2015 files being placed in the folder.
But here is another error:`Error in loadNamespace(x) :There is no package with the name 'sf'`.
Do you know what this is all about?

**Comment by Mbnl1197** [comment]
I installed the sf package. The program ran successfully. 
But it doesn't seem to mention that the sf package is needed.
